services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASS}
      - N8N_PORT=5678
    ports: ["5678:5678"]
    volumes:
      - /data:/data
      - n8n-data:/home/node/.n8n
  docsvc:
    build: ./work/docsvc
    environment:
      - DOCSVC_PORT=${DOCSVC_PORT:-8081}
    ports: ["8081:8081"]
    stdin_open: true   # для ввода в консоль
    tty: true          # для отображения
    volumes:
      - /data:/data
volumes:
  n8n-data:
